customhost = "internshipdbinstance.c7qv5pz2qhty.us-east-1.rds.amazonaws.com"
customuser = "Teohxinzhi123"
custompass = "Teohxinzhi123"
customdb = "internship"
custombucket = "teohxinzhi-internship-bucket"
customregion = "us-east-1"
